### ISSUE TITLE
NewAsterisk error

### ISSUE THREAD

**Issue by samuel1992** [warik/gami#1]
It returns "cannot use gami.NewAsterisk("192.168.0.10:8426", "userTest", "test") (type *gami.Asterisk) as type gami.Asterisk in assignment" when I try to use like this: 
`var a gami.Asterisk `
`  a = gami.NewAsterisk("192.168.0.10:8426","usertest","test")`

I was following the documentation for use it. Could you help me?

**Comment by a-urth** [comment]
You should use pointer on the left side of the assignment. Because `NewAsterisk` function call returns pointer to asterisk connection (so it can be created only once and reused for all project).

```go
var a *gami.Asterisk
a = gami.NewAsterisk("192.168.0.10:8426","usertest","test")
```

**Comment by samuel1992** [comment]
Thanks a lot! Im really new in Go, so sorry.

**Comment by a-urth** [comment]
No worries at all) Happy to help.
